### ISSUE TITLE
AttributeError: 'PromptGenerator' object has no attribute 'num_gpus'

### ISSUE THREAD

**Issue by qige96** [HKUST-KnowComp/FolkScope#3]
Running the script, reported such error:
```shell
(transformers) ricky@myremote:~/codespace/FolkScope$ bash scripts/run_generation.sh
Traceback (most recent call last):
  File "src/generator/generation.py", line 259, in <module>
    main()
  File "src/generator/generation.py", line 146, in main
    prompt_generator = PromptGenerator(args)
  File "src/generator/generation.py", line 62, in __init__
    if self.num_gpus != -1:
AttributeError: 'PromptGenerator' object has no attribute 'num_gpus'
```
Inspecting the [code](https://github.com/HKUST-KnowComp/FolkScope/blob/main/src/generator/generation.py#L62), I guess:

```python
                if self.num_gpus != -1:
```

should be 

```python
                if config.num_gpus != -1:
```

---

BTW, I adapt the script to this:

```shell
export TOKENIZERS_PARALLELISM=false

proj_dir=/home/ricky/codespace/FolkScope

CUDA_VISIBLE_DEVICES=0,1 python src/generator/generation.py \
  --data_dir $proj_dir/data \
  --output_dir $proj_dir/output \
  --model_name_or_path gpt2 \
  --model_type gpt2 \
  --max_seq_length 80 \
  --generation_type "inference" \
  --prompt_type "prefix" \
  --max_generation_length 100 \
  --num_generated_sent 3 \
  --batch_size 10 \
  --category "Clothing,-Shoes-&-Jewelry" \
  --num_samples 100 \
  --run_index 0 \
  --behavior_type buy
```

**Comment by ccclyu** [comment]
Thanks and also fixed!
