### ISSUE TITLE
lack data in amazon_title_category.txt

### ISSUE THREAD

**Issue by qige96** [HKUST-KnowComp/FolkScope#6]
```shell
(folkscope) ricky@myremote:~/codespace/FolkScope$ bash scripts/run_generation.sh
Sampling data from source metadata
Starting to sample 100000 examples from 0
Traceback (most recent call last):
  File "src/generator/generation.py", line 264, in <module>
    main()
  File "src/generator/generation.py", line 181, in main
    sampled_index = random.sample(range(len(all_examples)), args.num_samples)
  File "/home/ricky/.conda/envs/plm2kg/lib/python3.7/random.py", line 321, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```

The problem occurred because the list `all_example` is an empty list. Trace back, I found that `amazon_title_category.txt` is in lack of some data items. By the following debugging method, you can see that `item_b`s are never contained in `metainfo`.

https://github.com/HKUST-KnowComp/FolkScope/blob/main/src/generator/generation.py#L165

```python
          while True:
              line = source_file.readline() : str
              if not line:
                  break

              item_a, item_b = line.strip().split("\t")
              if item_a not in metainfo or item_b not in metainfo:
                  print('item_a not in metainfo', item_a not in metainfo)   # Added for debug
                  print('item_b', item_b not in metainfo)                   # Added for debug
                  continue
              if metainfo[item_a]["top_cate"] == args.category or metainfo[item_b]["top_cate"] == args.category:
                  all_examples.append((item_a, item_b))
```

```
......
item_a not in metainfo False
item_b True
item_a not in metainfo False
item_b True
item_a not in metainfo False
item_b True
item_a not in metainfo False
item_b True
item_a not in metainfo False
item_b True
item_a not in metainfo False
item_b True
item_a not in metainfo False
item_b True
......
```

Please check your data, or correct my replication step if I made any mistaks.

**Comment by ccclyu** [comment]
It is normal that some items may not have meta information as we sample `cobuy` pairs from the original amazon review dataset (https://nijianmo.github.io/amazon/index.html). Feel free to sample from it and generate the corresponding data as you want.
